#!/bin/bash
WEBHOST=$1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/admin > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/administrator > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/c > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/cart > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/css > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/i > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/images > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/js > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/logs > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/old > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/script > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/scripts > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/shop > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/store > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/temp > /dev/null 2>&1
wget -S -O /dev/null -a defdirs.txt $WEBHOST/tmp > /dev/null 2>&1
