#!/bin/bash
# ----------------------------------------------------
# simple check for frontpage extensions on a web server
# takes a uri in the form of "http://server.domain" as a param
# supports all the protocols wget does, since all this does
# is call wget a bunch of times.
# ----------------------------------------------------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------
# Copyright 2010 Jason Ross <algorythm /at/ gmail /dot/ com>
# ----------------------------------------------------
# version: 0.1
# ----------------------------------------------------

WEBHOST=$1
OUTPUT=fpdirs.txt

wget -S -O /dev/null -a $OUTPUT $WEBHOST/postinfo.html > /dev/null 2>&1
wget -S -O /dev/null -a $OUTPUT $WEBHOST/_vti_inf.html > /dev/null 2>&1
wget -S -O /dev/null -a $OUTPUT $WEBHOST/_vti_bin > /dev/null 2>&1
wget -S -O /dev/null -a $OUTPUT $WEBHOST/_vti_pvt > /dev/null 2>&1
wget -S -O /dev/null -a $OUTPUT $WEBHOST/cgi-bin/htimage.exe > /dev/null 2>&1
wget -S -O /dev/null -a $OUTPUT $WEBHOST/cgi-bin/imagemap.exe > /dev/null 2>&1
