#!/bin/bash
# ----------------------------------------------------
# a simple SIP OPTIONS scanner. presumes there's a file
# called 'servers.txt' in the current directory with
# a list of target hosts, one host per line.
# ----------------------------------------------------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------
# Copyright 2011 Jason Ross <algorythm /at/ gmail /dot/ com>
# ----------------------------------------------------
# version: 0.1
# ----------------------------------------------------

for i in `cat servers.txt`; do
echo "===================================";
echo "${i}";
echo "===================================";
echo -e "OPTIONS 1234567890@${i} SIP/2.0\nVia: SIP/2.0/UDP omg.sopwnd.com;branch=z9hG4bKhjhs8ass877\nMax-Forwards: 70\nTo: <sip:1234567890@${i}>\nFrom: Yo Mama <sip:yo.mama@omg.sopwnd.com>;tag=1928301774\nCall-ID: a84b4c76e66710\nCSeq: 63104 OPTIONS\nContact: <sip:yo.mama@omg.sopwnd.com>\nAccept: application/sdp\nContent-Length: 0\r\n" | nc -u ${i} ${1};
done;
