#!/usr/bin/perl -w
# ----------------------------------------------------
# simple file comparison tool
# ----------------------------------------------------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------
# Copyright 2010 Jason Ross <algorythm /at/ gmail /dot/ com>
# ----------------------------------------------------
# version: 0.1
# ----------------------------------------------------
use strict;

my $file1 = shift or &usage();
my $file2 = shift or &usage();

open(my $FILE1, "< $file1");
   my @file1 = <$FILE1>;
close($FILE1);

open(my $FILE2, "< $file2");
   my @file2 = <$FILE2>;
close($FILE2);

my(@union, @intersection, @difference, %count, $element);
@union = @intersection = @difference = ();

%count = ();
foreach $element (@file1, @file2) { $count{$element}++ }
foreach $element (keys %count) {
   push @union, $element;
   push @{ $count{$element} > 1 ? \@intersection : \@difference }, $element;
}  

print @difference;

sub usage() {
   print "
      fcmp compares 2 files and spits out the difference.
      usage:

         fcmp file1 file2

   ";
   exit 0;
}
