#!/bin/bash
# ----------------------------------------------------
# a very ugly bash script to
# automate dig requests to a nameserver
# 'nmap -sL' is a much more elegant way
# to do this, but sometimes nmap isn't
# available where dig (or host) is.
# this was written for those times.
# ----------------------------------------------------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------
# Copyright 2010 Jason Ross <algorythm /at/ gmail /dot/ com>
# ----------------------------------------------------
# version: 0.1
# ----------------------------------------------------
BASE="10.1"                # base network
ESAB="1.10.in-addr-arpa"   # for reverse lookups
NS="10.1.0.53"             # nameserver

for i in `seq 0 255`; do
for j in `seq 0 255`; do
echo $BASE.$i.$j >>$BASE
#echo "dig @$NS -t PTR $j.$i.$ESAB +short >>$BASE;sleep 10" >>$BASE
dig @$NS -t PTR $j.$i.$ESAB +short >>$BASE;sleep 10
done
done

