#!/bin/bash
# ----------------------------------------------------
# script to set up for a
# basic network scan and pentest
# ----------------------------------------------------
# presumes:
#   * it's being run in a directory empty except for:
#   * a targets.txt file with target hosts listed 1 IP per line
# ----------------------------------------------------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------
# Copyright 2010 - 2014 Jason Ross <algorythm /at/ gmail /dot/ com>
# ----------------------------------------------------
# version: 0.3
# ----------------------------------------------------
iface="eth0"
targets="targets.txt"

# create the directory structure
mkdir nmap svcs
mkdir nmap/output

# -------------------------------------
# create the top 1000 ports script
echo -e "#!/bin/bash\nsudo nmap -e ${iface} -A -sS -n -T4 --host-timeout 120 --max-retries 3 --top-ports 1000 -O --osscan-limit --open --reason -vvv -oA output/initial_scan -iL ${targets}" > nmap/top1k
chmod +x nmap/top1k

# create the authentication services script
echo -e "#!/bin/bash\nsudo nmap -e ${iface} -n -sS -T4 --host-timeout 120 --max-retries 3 --open --reason -vvv -pT:49,65,389,636,1812,1813 -oA output/auth_svcs -iL ${targets}" > nmap/auth_svcs_scan
chmod +x nmap/auth_svcs_scan

# create the selected UDP ports script
echo -e "sudo nmap -e ${iface} -n -sU -T4 --host-timeout 120 --max-retries 3 -pU:49,53,65,69,111,123,137,139,161,1812,1813,5060 -oA output/select_udp -iL ${targets}" > nmap/select_udp_scan
chmod +x nmap/select_udp_scan

# create the ping sweep script
echo -e "sudo nmap -sP -iL ../targets.txt -oG output/ping_sweep" > nmap/ping_sweep
chmod +x nmap/ping_sweep

# create the icmp_scans script
echo -e "#!/bin/bash\nsudo nmap -e ${iface} -PE -oA output/icmp_echo -iL ${targets}\n\nsudo nmap -e ${iface} -PP -oA output/icmp_timestamp -iL ${targets}\n\nsudo nmap -e ${iface} -PM -oA output/icmp_netmask -iL ${targets}\n" > nmap/icmp_scans
chmod +x nmap/icmp_scans
